# Generated by Django 5.0.1 on 2026-05-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('parent_contact', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(choices=[('Tuition', 'Tuition Fee'), ('Exam', 'Exam Fee'), ('Library', 'Library Fee'), ('Sports', 'Sports Fee')], max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('period1', models.CharField(blank=True, max_length=50)),
                ('period2', models.CharField(blank=True, max_length=50)),
                ('period3', models.CharField(blank=True, max_length=50)),
                ('period4', models.CharField(blank=True, max_length=50)),
                ('period5', models.CharField(blank=True, max_length=50)),
                ('period6', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('class_name', 'day')},
            },
        ),
    ]
